import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import benny from './images/benny-sq.webp'
import Button from '@/app/components/Button'
import dynamic from 'next/dynamic'
const CommentSection = dynamic(() => import('../CommentSection'), {
  ssr: false,
})

export const metadata = {
  title: 'Benny is Battling Cancer',
  // description: 'Generated by create next app',
}

const BennyRecipient = () => {
  console.log('Benny rendered')
  const id = '7532116d-3d20-4021-951b-7baf9e936019'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:py-[42px]">
        <div className={'flex text-primary items-center justify-between'}>
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto  font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Benny is Battling Cancer
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/recipients'} className="hover:underline">
                Recipients
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Benny is Battling Cancer
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'flex flex-col md:flex-row gap-[31px] pb-[50px]'}>
          <div className={'group relative w-fit p-[6px] shadow-sm'}>
            <Link href={'/recipients/benny'} className="relative">
              <Image
                src={benny}
                placeholder="blur"
                alt="profile picture of benny"
                className=" min-w-full md:min-w-[300px] lg:min-w-[391px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[55px]'}>
              Three year old Benny was recently diagnosed with cancer. While
              hospitalized with what was thought to be a bad ear infection,
              doctors discovered a tumor pressing against his skull. Since then,
              Benny has undergone a whirlwind of procedures, hospital
              admissions, and both chemotherapy and radiation therapy. He’s
              faced each challenge bravely, like a real trooper.
            </p>
            <Link href={'/recipients/benny'}>
              <Button className="mx-auto text-balance">
                Click here to go to Benny’s Love Transfusion page
              </Button>
            </Link>
          </div>
        </div>
        <CommentSection id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default BennyRecipient
