import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Damian from './images/Damian.webp'
import CommentAndHeartContainer from '../CommentAndHeartContainer'

export const metadata = {
  title: 'Damian is Battling Retinoblastoma Again',
  // description: 'Generated by create next app',
}

const DamianRecipient = () => {
  const id = '964fdf5f-6ae0-4b84-a663-c9ef48bc0804'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Damian is Battling Retinoblastoma Again
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Damian is Battling Retinoblastoma Again
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[43px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Image
              src={Damian}
              placeholder="blur"
              alt="profile picture of Damian"
              className="min-w-full md:min-w-[250px] lg:min-w-[379px] h-auto"
            />
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
              Our sweet friend Damian has been courageously battling
              retinoblastoma (pediatric eye cancer) and we are sad to say is
              nearing the end of his long battle. He is in a lot of pain and
              very uncomfortable.
            </p>
            <p className={'mb-[11px]'}>
              11/4/16 UPDATE:{' '}
              <span className="italic">
                “At 10:26 pm, my little Spiderman took his last breath after
                fighting for 2 days. He gasped and struggled for 2 days, but
                tonight, he is pain free and has gained his perfect angel wings.
                I could not be more proud of my superhero, he fought an amazing,
                hard battle for 2 1/2 years.”
              </span>
            </p>
            <p className={'mb-[11px]'}>
              Damian’s Facebook Page: {''}
              <Link
                href="https://www.facebook.com/GoTeamDamian/"
                target="_blank"
                className="text-primary underline"
              >
                Team Damian
              </Link>
            </p>
            <p className={'mb-[11px]'}>
              Please join us in surrounding Damian’s family with a huge virtual
              group hug of love and comfort by clicking the heart below (equals
              a hug), Comment or Share.
            </p>
          </div>
        </div>
        <CommentAndHeartContainer id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default DamianRecipient
