import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Sydney from './images/Sydney-300x300.webp'
import CommentAndHeartContainer from '../CommentAndHeartContainer'

export const metadata = {
  title: 'Sydney is Battling Brain Cancer',
  // description: 'Generated by create next app',
}

const SydneyRecipient = () => {
  const id = '8aacfb85-a9d1-46f1-9ad0-220eb52edf89'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:py-[42px]">
        <div className={'flex text-primary items-center justify-between'}>
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Sydney is Battling Brain Cancer
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Sydney is Battling DIPG (Brain Cancer)
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[43px]'}>
          <div
            className={
              'group relative w-fit p-[6px] mt-[-6px] ml-[-6px]  shadow-sm md:float-left md:mr-6 mb-6'
            }
          >
            <Link href={'/recipients/Sydney'} className="relative">
              <Image
                src={Sydney}
                placeholder="blur"
                alt="profile picture of Sydney"
                className="min-w-full lg:min-w-[294px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <p className={'mb-[11px]'}>
            Sydney is a 6 year old battling DIPG (a rare and aggressive form of
            childhood brain cancer).
          </p>
          <p className={'mb-[11px]'}>
            From Sydney’s Page:{' '}
            <span className="italic">
              “Sydney is a 6yr old beautiful, sassy, smart little girl. Two
              weeks ago Sydney started experiencing some vision changes and
              balance issues. Her mom took her to the ER to have her checked
              out. After doing a CT scan they told her mom (Pamela) that they
              found a mass on her brainstem. The doctors recommended a MRI to
              determine what this was and after that she was diagnosed with a
              very rare and aggressive form of childhood brain cancer (DIPG)
              This cancer is very aggressive and there is no cure. They gave her
              parents an estimated time that they will have left with Sydney
              they refuse to settle for that so they are keeping the faith and
              letting God have that say. But after this news they immediately
              reached out to the Children’s National Hospital in Washington DC
              where they have doctors that specialize in this. They will be
              going through radiation at VCU medical center and a medical trial
              at the children’s National hospital in Washington DC. They want to
              try and make Sydney as happy and comfortable as she can be. So we
              are asking for everyone our community and surrounding communities
              to please come together and help out this family. They will have
              medical expenses, travel expenses, bills, and also they are trying
              to take Sydney places that she has never been to and wants to
              experience. Thank you in advance for any aid you can donate to the
              family that so many of us know and love. Sidney, Pam, Sydney, and
              Emerson, are incredibly grateful for any support or prayers that
              you can offer as they continue to help Sydney fight against
              cancer.”
            </span>
          </p>
          <p className={'mb-[11px]'}>
            More info:<br></br>–{' '}
            <Link
              href="https://www.gofundme.com/f/lets-help-6yr-old-sydneys-fight-against-dipg"
              target="_blank"
              className="text-primary underline"
            >
              Sydney’s GoFundMe
            </Link>
            <br></br>–{' '}
            <Link
              href="https://www.wtvr.com/news/local-news/community-rallies-around-young-girl-with-rare-brain-cancer"
              target="_blank"
              className="text-primary underline"
            >
              Local News Article
            </Link>
          </p>
          <p className={'mb-[11px]'}>
            Please let Sydney and her family know she is in your thoughts and
            prayers by clicking the heart below (equals a hug), Comment or
            Share.
          </p>
        </div>
        <CommentAndHeartContainer id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default SydneyRecipient
