import DashboardHeader from './(dashboardHeader)/DashboardHeader'
import DashboardMenuDesktop from './(dashboardMenu)/DashboardMenuDesktop'
import DashboardMenuMobile from './(dashboardMenu)/DashboardMenuMobile'
import { openSans } from '@/utilities/fonts/fonts'

export const revalidate = 30

export const metadata = {
  title: {
    default: `Dashboard`,
    template: `%s - Love Transfusion`,
  },
  // description: 'Generated by create next app',
}

export default async function DashboardLayout({ children }) {
  return (
    <div className={`block md:flex h-screen ${openSans.className}`}>
      <div className={'hidden lg:block'}>
        <DashboardMenuDesktop />
      </div>
      <div className={'block lg:hidden'}>
        <DashboardMenuMobile />
      </div>
      <div className={'flex flex-col w-full lg:gap-5 lg:bg-[#F7F7F7]'}>
        <DashboardHeader />
        <div
          className={
            'lg:px-5 max-h-screen border-t-[1px] border-[#F7F7F7] lg:border-t-none overflow-y-auto box-border'
          }
        >
          <div
            className={
              'flex bg-white lg:rounded-md pt-[86px] pb-5 px-5 md:px-5 md:py-5 lg:p-8 lg:shadow-sm'
            }
          >
            {children}
          </div>
        </div>
      </div>
    </div>
  )
}
