import { createServer } from '@/config/supabase/supabaseServer'
import DashboardMenu from './DashboardMenu'
import DashboardHeader from './DashboardHeader'

export const metadata = {
  title: 'Dashboard',
  title: {
    default: `Love Transfusion`,
    template: `%s - Love Transfusion`,
  },
  // description: 'Generated by create next app',
}

export default async function DashboardLayout({ children }) {
  const supabase = createServer()
  const { data: user } = await supabase.from('users').select('*')
  const { avatar, display_name } = user[0]
  return (
    <>
      <div className={'flex h-[100vh]'}>
        <div className={'bg-primary text-white w-[360px] py-10 px-5'}>
          <DashboardMenu />
        </div>
        <div className={'flex flex-col w-full gap-5 bg-[#F7F7F7]'}>
          <DashboardHeader parameters={{ display_name, avatar }} />
          <div className={'px-5'}>
            <div className={'flex bg-white rounded-md py-10 px-5 shadow-sm'}>
              {children}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
