import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Mickey from './images/mickey100-300x300.webp'
import CommentAndHeartContainer from '../CommentAndHeartContainer'

export const metadata = {
  title: 'Mickey is Battling Brain Cancer',
  // description: 'Generated by create next app',
}

const MickeyRecipient = () => {
  const id = 'b461c138-8a11-4851-bfc4-5e5ad295b2bf'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Mickey is Battling Sanfilippo Syndrome
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Mickey is Battling Sanfilippo Syndrome
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[43px]'}>
          <div
            className={
              'group relative w-fit p-[6px] mt-[-6px] ml-[-6px]  shadow-sm md:float-left md:mr-6 mb-6'
            }
          >
            <Image
              src={Mickey}
              placeholder="blur"
              alt="profile picture of Mickey"
              className="min-w-full lg:min-w-[294px] h-auto"
            />
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <p className={'mb-[11px]'}>
            Michaela (“Mickey”) is 3 years old and was diagnosed with Sanfilippo
            Syndrome (also known as MPS III), a rare genetic disorder sometimes
            referred to as childhood Alzheimer’s. Mickey has subtype-A which is
            the most common and also, unfortunately, the most severe. She is a
            bubbly, delightful little girl with a big belly laugh and a giant
            smile she shares with everyone. She loves her Bear and likes to show
            off “her baby” little sister Maya.
          </p>
          <p className={'mb-[11px]'}>
            More Information:<br></br>–{' '}
            <Link
              href="https://www.youcaring.com/michaelamerrill-942623"
              target="_blank"
              className="text-primary underline"
            >
              Help Michaela Beat Sanfilippo (MPS III)!
            </Link>
            <br></br>–{' '}
            <Link
              href="https://savemickey.com/"
              target="_blank"
              className="text-primary underline"
            >
              Save Mickey
            </Link>
          </p>
          <p className={'mb-[11px]'}>
            From Mickey’s Parents:{' '}
            <span className="italic">
              “Michaela was a happy, seemingly quite healthy baby. As the
              disease progressed, however, she began to lag behind
              developmentally, especially in speech. It was determined that she
              has hearing loss and is nearsighted, and testing was performed to
              see if these issues were related. The testing unexpectedly
              discovered that she has Sanfilippo.
            </span>
          </p>

          <p className={'mb-[11px] italic'}>
            As the disease progresses, children with Sanfilippo like Mickey lose
            their abilities to speak and understand, to walk, and to eat. The
            current life expectancy is 10-20 years. Currently there is no
            treatment or cure, but promising research is happening as we speak
            in both the US and abroad, so there is still hope for her. Her
            family and friends are working hard to get Mickey admitted into a
            clinical trial as soon as possible. With the degenerative nature of
            this illness, time is precious.
          </p>
          <p className={'mb-[11px] italic'}>
            Since it is a rare disease, only 1 in 70,000 births, much of the
            research that has been done has been privately funded by dedicated
            foundations like the{' '}
            <Link
              href="http://teamsanfilippo.org/"
              target="_blank"
              className="text-primary underline"
            >
              Team Sanfilippo Foundation
            </Link>
            . We are raising funds to contribute to the Foundation in order to
            find a cure and treatments for Michaela and all kids like her who
            have this terrible disease. We also need to raise funds to travel to
            wherever in the world we are able to get her into treatment-
            expenses like passports, visas, and airfare.
          </p>
          <p className={'mb-[11px] italic'}>
            Thank you for taking the time to read about Michaela and help us.”
          </p>
          <p className={'mb-[11px]'}>
            Please let Mickey and her family know she is in your thoughts and
            prayers by clicking the heart below (equals a hug), Comment or
            Share.
          </p>
        </div>
        <CommentAndHeartContainer id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default MickeyRecipient
