import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Amy from './images/Amy.webp'
import CommentAndHeartContainer from '../CommentAndHeartContainer'

export const metadata = {
  title: 'Amy is Battling Serious Health Issues',
  // description: 'Generated by create next app',
}

const AmyRecipient = () => {
  const id = '8ed6e09e-6dbd-4606-a194-bc7215ee0c51'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Amy is Battling Serious Health Issues
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Amy is Battling Serious Health Issues
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[43px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Image
              src={Amy}
              placeholder="blur"
              alt="profile picture of Amy"
              className="min-w-full md:min-w-[250px] lg:min-w-[342px] h-auto"
            />
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
              Our friend Amy has been fiercely battling very complex severe
              intestinal dysmotility for many years. She recently had another
              surgery to repair a twisted small intestine, a hernia repair and a
              section of her small intestines was removed.
            </p>

            <p className={'mb-[11px]'}>
              Amy’s Facebook Page: {''}
              <Link
                href="https://www.facebook.com/theamymayyamfund/"
                target="_blank"
                className="text-primary underline"
              >
                The Amy May Yam Page
              </Link>
            </p>
            <p className={'mb-[11px]'}>
              Please let Amy and her family know she is in your thoughts and
              prayers by clicking the heart below (equals a hug), Comment or
              Share.
            </p>
          </div>
        </div>
        <CommentAndHeartContainer id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default AmyRecipient
