export const formatPageDescription = (data) => {
  return data
    ?.replaceAll('<br>', '')
    ?.replaceAll('<p>', '')
    ?.replaceAll('</p>', '')
    ?.replaceAll('<strong>', '')
    ?.replaceAll('</strong>', '')
    ?.replaceAll('<s>', '')
    ?.replaceAll('</s>', '')
    ?.replaceAll('<em>', '')
    ?.replaceAll('</em>', '')
    ?.replaceAll('<h1>', '')
    ?.replaceAll('</h1>', '')
    ?.replaceAll('<h2>', '')
    ?.replaceAll('</h2>', '')
    ?.replaceAll('<h3>', '')
    ?.replaceAll('</h3>', '')
    ?.replaceAll('<h4>', '')
    ?.replaceAll('<h4>', '')
    ?.replaceAll('<h5>', '')
    ?.replaceAll('</h5>', '')
    ?.replaceAll('</h6>', '')
    ?.replaceAll('</h6>', '')
    ?.replaceAll('<u>', '')
    ?.replaceAll('</u>', '')
    ?.replaceAll('&nbsp;', ' ')
}
