import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Marik from './images/Marik-300x300.webp'
import dynamic from 'next/dynamic'
const CommentSection = dynamic(() => import('../CommentSection'), {
  ssr: false,
})

export const metadata = {
  title: 'Marik is Battling Osteosarcoma Again',
  // description: 'Generated by create next app',
}

const MarikRecipient = () => {
  const id = 'a78ee787-0932-489a-a865-e115a9b17a4a'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Marik is Battling Osteosarcoma Again
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Marik is Battling Osteosarcoma Again
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[50px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Link href={'/recipients/Marik'} className="relative">
              <Image
                src={Marik}
                placeholder="blur"
                alt="profile picture of Marik"
                className="min-w-full md:min-w-[250px] lg:min-w-[300px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
              Many of you may remember our friend Marik who was diagnosed with
              and lost his leg to Osteosarcoma (a type of bone cancer) a few
              years back. He is an amazing young man and has inspired people
              around the globe with his story. Unfortunately the cancer has
              returned and he is battling it once again.
            </p>
            <p className={'mb-[11px]'}>
              Marik’s Facebook page: {''}
              <Link
                href="https://www.facebook.com/MiraclesForMarik/"
                target="_blank"
                className="text-primary underline"
              >
                Miracles for Marik
              </Link>
            </p>
            <p className={'mb-[11px]'}>
              Please let Marik and his family know he is in your thoughts and
              prayers by clicking the heart below (equals a hug), Comment or
              Share.
            </p>
          </div>
        </div>
        <CommentSection id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default MarikRecipient
