import TanstackProvider from '@/config/providers/TanstackProvider'
import './globals.css'
import {
  franklinGothicBook,
  franklinGothicDemiCond,
  franklinGothicMediumCond,
} from '@/utilities/fonts/fonts'
import MainNavigation from './components/ThisWebsiteOnly/Navigation/MainNavigation'
import Footer from './components/ThisWebsiteOnly/Footer/Footer'

export const metadata = {
  title: 'Social Support - Love Transfusion',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${franklinGothicBook.variable} ${franklinGothicDemiCond.variable} ${franklinGothicMediumCond.variable}`}
    >
      <body>
        <TanstackProvider>
          <MainNavigation />
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  )
}
