import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Justin from './images/justin.webp'
import dynamic from 'next/dynamic'
const CommentSection = dynamic(() => import('../CommentSection'), {
  ssr: false,
})

export const metadata = {
  title: 'Justin is Battling Cancer Again',
  // description: 'Generated by create next app',
}

const JustinRecipient = () => {
  const id = '4b3826b2-4dfc-48be-afdd-ad3c53fe8843'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Justin is Battling Cancer Again
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Justin is Battling Cancer Again
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[50px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Link href={'/recipients/Justin'} className="relative">
              <Image
                src={Justin}
                placeholder="blur"
                alt="profile picture of Justin"
                className="min-w-full md:min-w-[250px] lg:min-w-[374px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
            Many of you may remember our friend Justin who battled and overcame leukemia a few years back. Unfortunately cancer has returned. It is a very rare form of bladder cancer. Justin had surgery yesterday to remove part of his bladder, and is in a great deal of pain.
            </p>

            <p className={'mb-[11px]'}>
            Justin’s Facebook page: {''}
              <Link
                href="https://www.facebook.com/Prayers-for-Justin-228001227239480/"
                target="_blank"
                className="text-primary underline"
              >
                Prayers for Justin
              </Link>
            </p>
            <p className={'mb-[11px]'}>
            Please let Justin and his family know he is in your thoughts and prayers by clicking the heart below (equals a hug), Comment or Share.
            </p>
          </div>
        </div>
        <CommentSection id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default JustinRecipient
