import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Sammy from './images/Sammy.webp'
import dynamic from 'next/dynamic'
const CommentSection = dynamic(() => import('../CommentSection'), {
  ssr: false,
})

export const metadata = {
  title: 'Sammy is Battling Neuroblastoma',
  // description: 'Generated by create next app',
}

const SammyRecipient = () => {
  const id = '13d46697-4ea5-4e90-b80b-fab16341de26'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Sammy is Battling Neuroblastoma Again
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Sammy is Battling Neuroblastoma
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[50px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Link href={'/recipients/Sammy'} className="relative">
              <Image
                src={Sammy}
                placeholder="blur"
                alt="profile picture of Sammy"
                className="min-w-full md:min-w-[250px] lg:min-w-[335px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
              Our sweet friend Sammy has been courageously battling
              neuroblastoma (pediatric cancer) for almost 5 years, and we are
              sad to say it appears he is nearing the end of his long battle. He
              is in a lot of pain and very uncomfortable.
            </p>
            <p className={'mb-[11px]'}>
              Sammy’s Facebook Page: {''}
              <Link
                href="https://www.facebook.com/TeamSuperSammy/"
                target="_blank"
                className="text-primary underline"
              >
                Super Sammy
              </Link>
            </p>
            <p className={'mb-[11px]'}>
              Please let Sammy and his family know he is in your thoughts and
              prayers by clicking the heart below (equals a hug), Comment or
              Share.
            </p>
          </div>
        </div>
        <CommentSection id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default SammyRecipient
