import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Ayden from './images/Ayden.webp'
import CommentAndHeartContainer from '../CommentAndHeartContainer'

export const metadata = {
  title: 'Ayden is Battling Neuroblastoma Again',
  // description: 'Generated by create next app',
}

const AydenRecipient = () => {
  const id = '99a2f4d4-2eca-450a-8c28-03b193416b74'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Ayden is Battling Neuroblastoma Again
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Ayden is Battling Neuroblastoma Again
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[43px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Link href={'/recipients/Ayden'} className="relative">
              <Image
                src={Ayden}
                placeholder="blur"
                alt="profile picture of Ayden"
                className="min-w-full md:min-w-[250px] lg:min-w-[343px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
              Great News! Our buddy Ayden’s results from last week’s biopsies
              and scans are in. The current treatment is working! Ayden’s
              neuroblastoma cancer is stable and dissipating.
            </p>

            <p className={'mb-[11px]'}>
              Ayden’s Facebook Page: {''}
              <Link
                href="https://www.facebook.com/AydenAtticusAngels/"
                target="_blank"
                className="text-primary underline"
              >
                Ayden Atticus’Angels
              </Link>
            </p>
            <p className={'mb-[11px]'}>
              Please let Ayden and his family know he is in your thoughts and
              prayers by clicking the heart below (equals a hug), Comment or
              Share.
            </p>
          </div>
        </div>
        <CommentAndHeartContainer id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default AydenRecipient
