import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import Brody from './images/Brody.webp'
import CommentAndHeartContainer from '../CommentAndHeartContainer'

export const metadata = {
  title: 'Brody is Battling Neuroblastoma',
  // description: 'Generated by create next app',
}

const BrodyRecipient = () => {
  const id = '82f01a7b-901c-4fed-b356-6f87194ca986'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Brody is 5 Years Cancer Free!
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Brody is 5 Years Cancer Free!
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[43px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Link href={'/recipients/Brody'} className="relative">
              <Image
                src={Brody}
                placeholder="blur"
                alt="profile picture of Brody"
                className="min-w-full md:min-w-[250px] lg:min-w-[301px] lg:w-[301px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
              Awesome news for Brody! He is 5 years cancer free from battling
              AT/RT (an extremely rare and aggressive form of brain cancer).
            </p>
            <p className={'mb-[11px]'}>
              Brody’s Facebook page: {''}
              <Link
                href="https://www.facebook.com/Blossoms-for-Brody-170995623005581/"
                target="_blank"
                className="text-primary underline"
              >
                Blossoms for Brody
              </Link>
            </p>
            <p className={'mb-[11px]'}>
              Please show Brody and his family your continued support by
              clicking the heart below (equals a hug), Comment or Share.
            </p>
          </div>
        </div>
        <CommentAndHeartContainer id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default BrodyRecipient
