import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import David from './images/David.webp'
import CommentAndHeartContainer from '../CommentAndHeartContainer'

export const metadata = {
  title: 'David Got A Kidney Transplant',
  // description: 'Generated by create next app',
}

const DavidRecipient = () => {
  const id = '2cd90aac-3107-45d1-9df1-3af1d1163ac1'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:pt-[28px] md:pb-[35px]">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'py-2 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            David Got A Kidney Transplant
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              David Got A Kidney Transplant
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'pb-[43px] flex flex-col md:flex-row gap-6'}>
          <div
            className={
              'group relative w-fit p-[6px] shadow-sm md:mt-[-6px] md:ml-[-6px]'
            }
          >
            <Image
              src={David}
              placeholder="blur"
              alt="profile picture of David"
              className="min-w-full md:min-w-[250px] lg:min-w-[294px] h-auto"
            />
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={''}>
            <p className={'mb-[11px]'}>
              GREAT NEWS! After many years, a kidney has been found for David
              and he is finally getting a kidney!
            </p>
            <p className={'mb-[11px]'}>
              From David’s Facebook Page:{' '}
              <span className="italic">
                “Carol received a call 4 o’clock this morning that they have a
                kidney for David. He is in surgery, please pray for him, his
                mom, the surgeons, the nurses and all his caregivers. Thank
                you!”
              </span>
            </p>
            <p className={'mb-[11px]'}>
              For updates on David: {''}
              <Link
                href="https://www.facebook.com/DonorForDavidHodges/"
                target="_blank"
                className="text-primary underline"
              >
                Donor for David
              </Link>
            </p>
            <p className={'mb-[11px]'}>
              Please let David and his family know he is in your thoughts and
              prayers by clicking the heart below (equals a hug), Comment or
              Share.
            </p>
          </div>
        </div>
        <CommentAndHeartContainer />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default DavidRecipient
