import { openSans } from '@/utilities/fonts/fonts'
import Link from 'next/link'
import TitleSectionComponent from '@/app/components/ThisWebsiteOnly/TitleSectionComponent'
import ContentContainerWithSidebar from '@/app/components/ThisWebsiteOnly/ContentContainerWithSidebar/ContentContainerWithSidebar'
import Image from 'next/image'
import miguel from './images/Mighty-Miguel.webp'
import dynamic from 'next/dynamic'
const CommentSection = dynamic(() => import('../CommentSection'), {
  ssr: false,
})

export const metadata = {
  title: 'Miguel is Battling a Brain Tumor and Seizures',
  // description: 'Generated by create next app',
}

const MiguelRecipient = () => {
  const id = '8c46271e-ebe9-457f-aa18-96263ee50057'
  return (
    <div className={`${openSans.className}`}>
      <TitleSectionComponent className="md:py-[42px] md:pt-7">
        <div
          className={'flex flex-col text-primary items-center justify-between'}
        >
          <h1
            className={
              'pt-2 pb-1 max-sm:text-center text-[30px] max-sm:mx-auto font-semibold leading-[40px] md:leading-[50px]'
            }
          >
            Miguel is Battling a Brain Tumor and Seizures
          </h1>
          <div className={'hidden gap-2 md:flex'}>
            <p className={'text-[13px] leading-[20px]'}>
              <Link href={'/'} className="hover:underline">
                Home
              </Link>
            </p>
            <p className={'text-[13px] leading-[20px]'}>/</p>
            <p className={'text-[13px] leading-[20px]'}>
              Miguel is Battling a Brain Tumor and Seizures
            </p>
          </div>
        </div>
      </TitleSectionComponent>
      <ContentContainerWithSidebar className={'text-[15px]'}>
        <div className={'flex flex-col md:flex-row gap-[24px] pb-[50px]'}>
          <div
            className={
              'group relative w-fit p-[6px] md:ml-[-6px] md:mt-[-6px] shadow-sm'
            }
          >
            <Link href={'/recipients/miguel'} className="relative">
              <Image
                src={miguel}
                placeholder="blur"
                alt="profile picture of miguel"
                className=" min-w-full md:min-w-[300px] lg:min-w-[274px] h-auto"
              />
            </Link>
            <div
              className={
                'opacity-0 group-hover:opacity-15 absolute top-0 left-0 w-full h-full bg-primary group-hover:transition-all group-hover:duration-500'
              }
            />
          </div>
          <div className={'flex flex-col gap-[11px]'}>
            <p className={''}>
              Miguel has been battling a brain tumor for years and is suffering
              from seizures and bad headaches.
            </p>
            <p className={''}>
              From Miguel’s Mom: “We got the results of the EEG and yes he is
              definitely having seizures. He needs to have labs tomorrow morning
              and then the doctor will go from there. Like I said previously he
              is already maxed out on 3 of the 5 medications so they are looking
              to see if he can be increased on the other ones or if he is maxed
              out according to his body. Today he is having some real bad
              headaches. He went to lay down after just getting up from a two
              hour nap which leads me to believe that he has been seizing while
              he sleeps.”
            </p>
            <p className={''}>
              Miguel’s Facebook Page:{' '}
              <Link
                href="https://www.facebook.com/MightyMiguel03/"
                target="_blank"
                className="text-primary underline"
              >
                Mighty Miguel
              </Link>
            </p>
            <p className={''}>
              Please let Miguel and his family know he is in your thoughts and
              prayers by clicking the heart below (equals a hug), Comment or
              Share.
            </p>
          </div>
        </div>
        <CommentSection id={id} />
      </ContentContainerWithSidebar>
    </div>
  )
}

export default MiguelRecipient
